name: Java CI

on:
  push:
    branches: 
      - main
      - feature/**
  pull_request:
    branches: 
      - main
      - feature/**

jobs:
  build:
    environment: sandbox-java
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set environment variable
      run: echo "PORT=8080" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get project name
      id: get_project_name
      run: echo "PROJECT_NAME=$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout)" >> $GITHUB_ENV

    - name: Echo project name
      run: |
        echo "Project Name: ${{ env.PROJECT_NAME }}"

    - name: Build and push Docker image
      run: |
        mvn compile jib:build -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }} -Dimage=${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
  